/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lmaoo.restocashier;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author seifer
 */
public class Payment extends javax.swing.JFrame {
    
    private final Order order;
    
    /**
     * Creates new form Payment
     * @param order 
     */
    public Payment(Order order) {
        this.order = order;
        initComponents();
        populateBillTable(order);
    }
    
    private void populateBillTable(Order o) {
        var model = (DefaultTableModel)tblBill.getModel();
        
        for (var p : order.products) {
            model.addRow(new Object[] {
                p.getName(),
                p.getQuantity(),
                p.getTotalAmount()
            });
        }
        
        lblAmount.setText(Double.toString(o.getTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        lblChangeFor = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        lblAmount = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        lblToPay1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Epic Restaurant Bill");

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBill);

        lblChangeFor.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblChangeFor.setText("Change For:");

        btnPay.setText("Charge");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        lblAmount.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAmount.setText("0.0");

        txtPay.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        txtPay.setText("0.0");

        lblToPay1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblToPay1.setText("To Pay:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblToPay1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPay)
                                    .addComponent(lblChangeFor, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblToPay1)
                            .addComponent(lblChangeFor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPay)
                            .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        var amountPayed = Double.parseDouble(txtPay.getText());
        if (amountPayed < order.getTotal()) {
            JOptionPane.showMessageDialog(this, "You do not have enough cash!", "Payment failed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DateTimeFormatter f = DateTimeFormatter.ofPattern("MM dd yyyy HH:mm:ss");
        Receipt rec = new Receipt();
        rec.Receipt();
        rec.setVisible(true);
        rec.lblDate.setText(f.format(LocalDateTime.now()));
        var m = (DefaultTableModel)rec.tblReceipt.getModel();
               
        for (var p : order.products) {
            m.addRow(new Object[] {
                p.getName(),
                p.getQuantity(),
                p.getTotalAmount(),
            });
        }
        
        rec.lblTotal.setText("Total amount: PHP " + order.getTotal());
        rec.lblPaid.setText("Amount paid: PHP " + amountPayed);
        var change = amountPayed - order.getTotal();
        rec.lblChange.setText("Change: PHP " + change);
        
        
//        rec.b.setText(rec.b.getText() + "            Item" + "\t\t" + "Quantity" + "\t" + "Price" + "\t\n");
//        rec.b.setText(rec.b.getText() + "=======================================================\n");
//        for (var p : order.products) {
//            String pName = p.getName();
//            String qty = Integer.toString(p.getQuantity());
//            String price = Double.toString(p.getPrice());
//            rec.b.setText(rec.b.getText() + "    " + pName + "    \t" + qty + "\t" + price + "\n");
//        }
//        rec.b.setText(rec.b.getText() + "=======================================================\n\n");
//        rec.b.setText(rec.b.getText() + "\t\tTotal Amount: " + order.getTotal() + "\n");
//        rec.b.setText(rec.b.getText() + "\t\tAmount Payed: " + txtPay.getText() + "\n");
//      
        dispose();
    }//GEN-LAST:event_btnPayActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Payment().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblChangeFor;
    private javax.swing.JLabel lblToPay1;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtPay;
    // End of variables declaration//GEN-END:variables
}
